//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MML_APP.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public string CODIGO { get; set; }
        public string PASSWO { get; set; }
        public string NOMBRE { get; set; }
        public string ABREVI { get; set; }
        public Nullable<System.DateTime> INICIO { get; set; }
        public string CARGO { get; set; }
        public string NIVEL { get; set; }
        public string OFICINA { get; set; }
        public string ESTADO { get; set; }
        public string C_USUARIO { get; set; }
        public Nullable<System.DateTime> F_CONTROL { get; set; }
        public string COD_MERCADO { get; set; }
    }
}
